name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create firebaseConfig.js
        run: |
          echo "${{ secrets.ENV_FILE }}" > /src/firebaseConfig.js
          working-directory: ${{ github.workspace }}
        
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUMO_NOTAS }}'
          channelId: live
          projectId: lumo-notas
