name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls

      - name: Print FIREBASE_CONFIG_JS
        run: echo "$FIREBASE_CONFIG_JS"
        
      - name: Create firebaseConfig.js
        run: echo "$FIREBASE_CONFIG_JS" > src/firebaseConfig.js
        env:
          FIREBASE_CONFIG_JS: ${{ secrets.FIREBASE_CONFIG_JS }}
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUMO_NOTAS }}'
          channelId: live
          projectId: lumo-notas